- name: Create Data Directory For MySQL
  file:
    path: "{{ container_data_dir }}/mysql/"
    state: directory
    recurse: yes
  tags:
    - mysql
    - mysql_dir
    - create_dirs
    - wordpress

- name: Create DB Directory For MySQL
  file:
    path: "{{ container_data_dir }}/mysql/db"
    state: directory
    recurse: yes
  tags:
    - mysql
    - mysql_dir
    - create_dirs
    - wordpress

- name: Create DB Directory For Wordpress
  file:
    path: "{{ container_data_dir }}/wordpress"
    state: directory
    recurse: yes
  tags:
    - wordpress_dir
    - create_dirs
    - wordpress

- name: Run Mysql Container
  docker_container:
    hostname: mysql
    name: mysql
    image: mysql:5.7
    state: started
    networks:
      - name: "{{ monitoring_docker_network }}"
      - name: "{{ traefik_docker_network }}"
    labels:
      traefik.enable: "false"
    env:
      MYSQL_DATABASE: "{{ mysql_db_name }}"
      MYSQL_USER: "{{ mysql_db_user }}"
      MYSQL_PASSWORD: "{{ mysql_db_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "{{ container_data_dir }}/mysql/db:/var/lib/mysql"
    restart_policy: unless-stopped
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
  tags:
    - mysql
    - mysql_container
    - wordpress

- name: Run Wordpress Container
  docker_container:
    hostname: wordpress
    name: wordpress
    image: wordpress
    state: started
    networks:
      - name: "{{ monitoring_docker_network }}"
      - name: "{{ traefik_docker_network }}"
    labels:
      traefik.backend: "wordpress"
      traefik.frontend.rule: "Host:{{ wordpress_dns_name }}"
      traefik.docker.network: "{{ traefik_docker_network }}"
      traefik.port: "80"
    env:
      WORDPRESS_DB_NAME: "{{ mysql_db_name }}"
      WORDPRESS_DB_USER: "{{ mysql_db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_db_password }}"
      WORDPRESS_DB_HOST: "{{ mysql_db_host }}"
    volumes:
      - "{{ container_data_dir }}/wordpress:/var/www/html"
    published_ports:
      - 8392:80
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
    restart_policy: unless-stopped
  tags:
    - wordpress
    - wordpress_container